In [135]:
# Importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [136]:
# Importing the dataset

df = pd.read_csv('KAG.csv')
df.sample(5)

date  Appliances  lights         T1       RH_1  \
4534   2016-02-12 04:40:00          60       0  21.100000  41.000000   
4121   2016-02-09 07:50:00          60       0  21.390000  42.790000   
13117  2016-04-11 19:10:00         140      30  22.790000  45.500000   
17048  2016-05-09 02:20:00          60       0  24.390000  38.433333   
8221   2016-03-08 19:10:00         110      20  20.033333  48.693333   

              T2       RH_2         T3       RH_3     T4  ...     T9  \
4534   20.290000  40.326667  21.200000  42.260000  19.70  ...  18.70   
4121   20.700000  41.730000  22.823333  42.566667  20.23  ...  19.10   
13117  21.926667  43.090000  23.200000  40.730000  22.10  ...  21.00   
17048  23.000000  37.760000  26.390000  38.200000  24.70  ...  23.29   
8221   17.963333  45.033333  20.100000  37.323333  18.79  ...  17.60   

            RH_9      T_out  Press_mm_hg     RH_out  Windspeed  Visibility  \
4534   45.000000   1.833333   746.500000  95.000000   2.666667   63.333333   
4121   47.090000   6.400000   740.166667  83.333333   5.500000   26.166667   
13117  42.090000  15.050000   750.566667  71.333333   0.833333   40.000000   
17048  44.321429  15.500000   751.766667  61.333333   2.000000   40.000000   
8221   36.030000   5.316667   757.166667  70.333333   3.000000   40.000000   

       Tdewpoint        rv1        rv2  
4534    1.133333  21.938961  21.938961  
4121    3.683333  37.104131  37.104131  
13117   9.833333   7.845923   7.845923  
17048   8.133333  12.054952  12.054952  
8221    0.283333  24.878199  24.878199  

[5 rows x 29 columns]

In [137]:
# Checking for null values

df.isna().any().any()

False

In [138]:
df.columns

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [139]:
df.dtypes

date            object
Appliances       int64
lights           int64
T1             float64
RH_1           float64
T2             float64
RH_2           float64
T3             float64
RH_3           float64
T4             float64
RH_4           float64
T5             float64
RH_5           float64
T6             float64
RH_6           float64
T7             float64
RH_7           float64
T8             float64
RH_8           float64
T9             float64
RH_9           float64
T_out          float64
Press_mm_hg    float64
RH_out         float64
Windspeed      float64
Visibility     float64
Tdewpoint      float64
rv1            float64
rv2            float64
dtype: object

In [140]:
df['lights'].unique()

array([30, 40, 50, 70, 60, 10, 20,  0], dtype=int64)

In [141]:
df['Appliances'].unique()

array([  60,   50,   70,  230,  580,  430,  250,  100,   90,   80,  140,
        120,  190,  110,  400,  390,  240,   40,   30,  310,  380,  370,
         20,  260,  500,  450,  220,  170,  290,  130,  200,  210,  180,
        350,  300,  340,  150,  330,  420,  520,  360,  270,  550,  690,
        620,  610,  490,  410,  320,  740,  910,  510,  790,  460,  160,
        480,  280,  560, 1080,  750,  470,  440,  800,  540,  530,  660,
        630,  600,   10,  570,  830, 1070,  890,  590,  850,  710,  680,
        670,  780,  640,  650,  700,  770,  720,  760,  860,  880,  730,
        900,  820,  870,  840], dtype=int64)

In [142]:
df['date'] = pd.to_datetime(df['date'], 
 format = '%Y-%m-%d %H:%M:%S', 
 errors = 'coerce')

In [143]:
df['date'].dtypes

dtype('<M8[ns]')

In [144]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['week'] = df['date'].dt.week
df['day'] = df['date'].dt.day
df['hour'] = df['date'].dt.hour
df['minute'] = df['date'].dt.minute
df['dayofweek'] = df['date'].dt.dayofweek

In [145]:
df.groupby('year').size()

year
2016    19735
dtype: int64

In [146]:
df.groupby('month').size()

month
1    2922
2    4176
3    4464
4    4320
5    3853
dtype: int64

In [147]:
df.groupby('week').size()

week
2      906
3     1008
4     1008
5     1008
6     1008
7     1008
8     1008
9     1008
10    1008
11    1008
12    1008
13    1008
14    1008
15    1008
16    1008
17    1008
18    1008
19    1008
20    1008
21     685
dtype: int64

In [148]:
df.groupby('day').size()

day
1     576
2     576
3     576
4     576
5     576
6     576
7     576
8     576
9     576
10    576
11    618
12    720
13    720
14    720
15    720
16    720
17    720
18    720
19    720
20    720
21    720
22    720
23    720
24    720
25    720
26    720
27    685
28    576
29    576
30    432
31    288
dtype: int64

In [149]:
df.groupby('hour').size()

hour
0     822
1     822
2     822
3     822
4     822
5     822
6     822
7     822
8     822
9     822
10    822
11    822
12    822
13    822
14    822
15    822
16    822
17    828
18    823
19    822
20    822
21    822
22    822
23    822
dtype: int64

In [150]:
df.groupby('minute').size()

minute
0     3290
10    3289
20    3289
30    3289
40    3289
50    3289
dtype: int64

In [151]:
df.groupby('dayofweek').size()

dayofweek
0    2778
1    2880
2    2880
3    2880
4    2845
5    2736
6    2736
dtype: int64

In [152]:
df.drop('year', axis = 1, inplace = True)
df.columns

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2', 'month', 'week', 'day', 'hour',
       'minute', 'dayofweek'],
      dtype='object')

In [153]:
df.drop('date', axis = 1, inplace = True)

In [156]:
df = df.sample(n = len(df), random_state = 1)
df = df.reset_index(drop = True)

In [157]:
X = df.drop('Appliances', axis = 1)
y = df.Appliances

In [158]:
X.head()

lights         T1    RH_1      T2       RH_2       T3       RH_3     T4  \
0       0  18.963333  42.090  18.290  41.290000  19.8900  43.200000  18.50   
1      20  22.600000  43.700  20.945  43.845000  23.2000  40.626667  22.70   
2       0  24.700000  40.745  23.290  39.230000  25.3900  38.545000  24.29   
3       0  20.025000  39.695  18.100  40.966667  20.7900  39.678000  18.60   
4       0  21.000000  33.790  19.500  34.000000  20.2675  35.608750  19.50   

        RH_4         T5  ...  Visibility  Tdewpoint        rv1        rv2  \
0  41.790000  17.790000  ...   30.000000   1.683333  19.215195  19.215195   
1  42.000000  21.100000  ...   40.000000   6.866667  17.428107  17.428107   
2  40.400000  24.290000  ...   28.166667   7.016667  20.378018  20.378018   
3  39.723333  18.600000  ...   21.666667   0.100000  22.965252  22.965252   
4  33.260000  17.777143  ...   22.000000  -1.400000  43.534302  43.534302   

   month  week  day  hour  minute  dayofweek  
0      1     2   14     2      10          3  
1      4    15   11    22      20          0  
2      5    21   24    20      10          1  
3      2     6   13     9      20          5  
4      2     7   17    16       0          2  

[5 rows x 33 columns]

In [159]:
y.head()

0     50
1     60
2    100
3    130
4     60
Name: Appliances, dtype: int64

In [160]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [161]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.preprocessing import StandardScaler
from sklearn import metrics

In [162]:
def return_R2(pred):
  return metrics.r2_score(y_test, pred)

In [163]:
# Comparing various regression models

def show_accuracy(train_X, train_y, test_X):
  r_LR = LinearRegression()
  r_DT = DecisionTreeRegressor(random_state = 0)
  r_SV = SVR(kernel = 'linear')
  r_RF = RandomForestRegressor(n_estimators = 10, random_state = 0)
  r_ET = ExtraTreesRegressor()

  # Feature scaling required only for linear regression and support vector

  sc_LR = StandardScaler()
  sc_SV = StandardScaler()

  r_LR.fit(sc_LR.fit_transform(train_X), train_y)
  r_DT.fit(train_X, train_y)
  r_SV.fit(sc_SV.fit_transform(train_X), train_y)
  r_RF.fit(train_X, train_y)
  r_ET.fit(train_X, train_y)

  pred_LR = r_LR.predict(sc_LR.transform(test_X))
  pred_DT = r_DT.predict(test_X)
  pred_SV = r_SV.predict(sc_SV.transform(test_X))
  pred_RF = r_RF.predict(test_X)
  pred_ET = r_ET.predict(test_X)

  print('Linear Regression - ', return_R2(pred_LR))
  print('Decision Tree - ', return_R2(pred_DT))
  print('Support Vector - ', return_R2(pred_SV))
  print('Random Forest - ', return_R2(pred_RF))
  print('Extra Trees - ', return_R2(pred_ET))

In [164]:
# Extra Trees Regressor shows the best test r2 score of .59

show_accuracy(X_train, y_train, X_test)

Linear Regression -  0.16981047507022173
Decision Tree -  0.23984130401610093
Support Vector -  0.02461710770471004
Random Forest -  0.4798799722485654
Extra Trees -  0.5914203643506489


In [165]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression

In [166]:
# Identifying inputs most relevant to target variable

def feature_selection(X_train, y_train, X_test):
    feat = SelectKBest(score_func=f_regression, k='all')
    feat.fit(X_train, y_train)
    return feat

In [167]:
feat = feature_selection(X_train, y_train, X_test)

In [168]:
X_trainls = X_train.copy()
X_testls = X_test.copy()
X_trainls.head()

lights         T1   RH_1         T2       RH_2         T3       RH_3  \
2510        0  20.000000  34.70  18.600000  35.290000  19.738571  35.700000   
8378        0  23.890000  40.09  25.500000  34.197143  24.390000  37.700000   
9339        0  18.963333  43.79  18.000000  44.163333  19.700000  43.590000   
10503       0  22.500000  41.23  21.133333  41.633333  23.963333  36.966667   
8505       10  19.890000  37.70  17.600000  39.700000  20.100000  39.333333   

          T4       RH_4         T5  ...  Visibility  Tdewpoint        rv1  \
2510   18.50  34.730000  17.251429  ...   22.333333   0.266667  21.743244   
8378   24.10  38.200000  20.361429  ...   30.833333   8.800000  17.887101   
9339   17.70  44.090000  17.066667  ...   27.833333   1.166667  10.903908   
10503  21.29  40.430000  20.700000  ...   40.000000   6.433333  13.121974   
8505   20.53  37.566667  17.730000  ...   47.500000  -0.300000  12.841131   

             rv2  month  week  day  hour  minute  dayofweek  
2510   21.743244      2     7   18    18      20          3  
8378   17.887101      5    20   17    14      50          1  
9339   10.903908      1     4   28    21      50          3  
10503  13.121974      4    14    5    17      10          1  
8505   12.841131      3    10    7     0      30          0  

[5 rows x 33 columns]

In [169]:
# Only considering features with score >= 100

i = 0
for feature in X_trainls.columns:
    if (feat.scores_[i] < 100):
        X_trainls.drop(feature, axis = 1, inplace = True)
        X_testls.drop(feature, axis = 1, inplace = True)
    i = i + 1;
X_trainls.columns    

Index(['lights', 'RH_1', 'T2', 'T3', 'T6', 'RH_6', 'RH_8', 'T_out', 'RH_out',
       'Windspeed', 'hour'],
      dtype='object')

In [170]:
# Extra again shows best performance with test r2 score of 0.57
# however less as compared to previous scenario

show_accuracy(X_trainls, y_train, X_testls)

Linear Regression -  0.1231355717508259
Decision Tree -  0.15206474214026444
Support Vector -  0.001088220313695487
Random Forest -  0.47141939885103057
Extra Trees -  0.574348108435707


In [171]:
# Feature scaling carried out before ANN

sc = StandardScaler()
X_trainS = sc.fit_transform(X_train)
X_testS = sc.transform(X_test)

In [172]:
X_trainS.shape

(15788, 33)

In [173]:
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(180, kernel_initializer='normal', activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(450, kernel_initializer='normal', activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(250, kernel_initializer='normal', activation='relu'),
    keras.layers.Dense(1, kernel_initializer='normal', activation='linear')
])

model.compile(
    loss='msle', 
    optimizer='adam',
    metrics=['msle']
)

model.fit(
    X_trainS, 
    y_train.values, 
    epochs=100
)

Epoch 1/100
15788/15788 [==============================] - 2s 136us/sample - loss: 0.6991 - msle: 0.6991
Epoch 2/100
15788/15788 [==============================] - 2s 118us/sample - loss: 0.3016 - msle: 0.3016
Epoch 3/100
15788/15788 [==============================] - 2s 114us/sample - loss: 0.2882 - msle: 0.2882
Epoch 4/100
15788/15788 [==============================] - 2s 125us/sample - loss: 0.2820 - msle: 0.2820
Epoch 5/100
15788/15788 [==============================] - 2s 116us/sample - loss: 0.2753 - msle: 0.2753
Epoch 6/100
15788/15788 [==============================] - 2s 107us/sample - loss: 0.2684 - msle: 0.2684
Epoch 7/100
15788/15788 [==============================] - 2s 109us/sample - loss: 0.2579 - msle: 0.2579
Epoch 8/100
15788/15788 [==============================] - 2s 111us/sample - loss: 0.2522 - msle: 0.2522
Epoch 9/100
15788/15788 [==============================] - 2s 113us/sample - loss: 0.2485 - msle: 0.2485
Epoch 10/100
15788/15788 [=============================

15788/15788 [==============================] - 2s 110us/sample - loss: 0.1243 - msle: 0.1243
Epoch 79/100
15788/15788 [==============================] - 2s 101us/sample - loss: 0.1231 - msle: 0.1231
Epoch 80/100
15788/15788 [==============================] - 2s 106us/sample - loss: 0.1199 - msle: 0.1199
Epoch 81/100
15788/15788 [==============================] - 2s 112us/sample - loss: 0.1219 - msle: 0.1219
Epoch 82/100
15788/15788 [==============================] - 2s 102us/sample - loss: 0.1219 - msle: 0.1219
Epoch 83/100
15788/15788 [==============================] - 2s 100us/sample - loss: 0.1201 - msle: 0.1201
Epoch 84/100
15788/15788 [==============================] - 2s 101us/sample - loss: 0.1183 - msle: 0.1183
Epoch 85/100
15788/15788 [==============================] - 2s 104us/sample - loss: 0.1187 - msle: 0.1187
Epoch 86/100
15788/15788 [==============================] - 2s 111us/sample - loss: 0.1150 - msle: 0.1150
Epoch 87/100
15788/15788 [==============================] -

In [174]:
y_train[:5]

2510      80
8378      50
9339      40
10503    260
8505      40
Name: Appliances, dtype: int64

In [175]:
X_trainS[:5]

array([[-0.4755545 , -1.0462285 , -1.38965143, -0.79058711, -1.25389866,
        -1.25439036, -1.08331774, -1.14964548, -0.98338301, -1.26358694,
        -0.90274597, -0.71157728,  0.39798022, -1.26157566, -1.23495128,
        -0.98685614, -1.11645688, -0.98154236, -1.52704993, -0.94909618,
         0.13814326,  0.46388575, -0.68873437, -1.35326797, -0.82793017,
        -0.22312659, -0.22312659, -0.8239546 , -0.77954969,  0.22884279,
         0.93742937, -0.29321352,  0.01425664],
       [-0.4755545 ,  1.36943446, -0.03708354,  2.34711816, -1.52201092,
         1.0535316 , -0.46891347,  1.58209534, -0.18484016,  0.41476148,
        -0.60261653,  2.13728684, -1.71835591,  1.33848983,  0.04275871,
         0.43913549, -0.52826863,  1.6348841 , -0.2319947 ,  1.67294149,
         0.33669907, -1.25979464,  0.39629904, -0.63372743,  1.2002818 ,
        -0.48931942, -0.48931942,  1.41414746,  1.51963404,  0.11045851,
         0.36066216,  1.46718265, -0.99058184],
       [-0.4755545 , -1.6899

In [176]:
pred = model.predict(X_testS)

In [177]:
np.around(pred[:5])

array([[ 46.],
       [147.],
       [ 93.],
       [152.],
       [ 38.]], dtype=float32)

In [178]:
# Shows r2 score of 0.39 lesser than previous two scenarios

metrics.r2_score(y_test, np.around(pred))

0.3981958968190926

In [179]:
y_test[:5]

343       50
13136    240
19315     80
4706     370
5322      30
Name: Appliances, dtype: int64

In [180]:
# Conclusion

# Thus the best test r2 score was obtained with Extra Trees Regressor 
# when all features were considered followed by Random Forest

# When Correlation Feature selection is carried out, 
# it results in a slight decrease in r2 score

# Also ANN carried out after feature selection doesn't 
# improve performance

# Best test set R2 score - .59